# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a695f9b5a6b6ab224f1633f6d674922a717a0d37e30817ce09b13331cd18f10a5fe8c60ff780de147740136ee28cf98e5560e17e1cc0cf754ac5e8d1bedce2f

test:
  secret_key_base: 0fc88e41beccbd55c8c4a1928775ed48ef5bc8a6c4bcd4d513bc61e76aa85dbee1f1e07845d9dc107c24fa8f70dbd54445be7159c1337b10e2986fc273c928db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
