//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Configuration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configuration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Configuration", typeof(Configuration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 360.
        /// </summary>
        internal static string BALL_POS_X {
            get {
                return ResourceManager.GetString("BALL_POS_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 260.
        /// </summary>
        internal static string BALL_POS_Y {
            get {
                return ResourceManager.GetString("BALL_POS_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string BALL_POS_Z {
            get {
                return ResourceManager.GetString("BALL_POS_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string NUM_BRICKS_X {
            get {
                return ResourceManager.GetString("NUM_BRICKS_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string NUM_BRICKS_Y {
            get {
                return ResourceManager.GetString("NUM_BRICKS_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string NUM_LIVES {
            get {
                return ResourceManager.GetString("NUM_LIVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string NUM_POINTS {
            get {
                return ResourceManager.GetString("NUM_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 360.
        /// </summary>
        internal static string PADDLE_POS_X {
            get {
                return ResourceManager.GetString("PADDLE_POS_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 395.
        /// </summary>
        internal static string PADDLE_POS_Y {
            get {
                return ResourceManager.GetString("PADDLE_POS_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string PADDLE_POS_Z {
            get {
                return ResourceManager.GetString("PADDLE_POS_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game.sav.
        /// </summary>
        internal static string SAVE_PATH {
            get {
                return ResourceManager.GetString("SAVE_PATH", resourceCulture);
            }
        }
    }
}
